# -- System Configuration -- #
RANDOM_SEED: 7

# -- Whole Slide Image loader configuration -- #
WSL_DATA_DIR: 'E:\Complete_Working_Data\CR07\Collated_Data\'
ASSOCIATED_FILE_PATTERN: 'scores.xml'

# -- Patch Extraction Configuration -- #
EXTRACTION_MODULE: 'PointAnnotationPatchExtractor'
PATCHES_DIR: 'E:\Complete_Working_Data\CR07\Patches\8px'
PATCH_SIZE: [ 512, 1024 ]
SCALING_FACTOR: 2
USE_CIR_MASK: True
CONTEXT_MASK_RADIUS: 8