# Format with backslash in paths.
CACHE: 'cache\'
DATA_DIR: 'data\development_data\'
PATCHES_DIR: 'data\patches\'

# Patch extraction configuration.
ASSOCIATED_FILE_PATTERN: 'w.*scores.xml'
DOWNSAMPLE_FACTOR: 2
PATCH_SIZE:
  WIDTH: 512
  HEIGHT: 1024