# Format with backslash in paths.
CACHE: 'cache\'
DATA_DIR: 'data\CR07\'
TRAINING_DATA: 'models\TrainingData.txt'
TEST_DATA: 'models\TestData.txt'
PATCHES_DIR: 'data\HGDL3\'
XML_DIRECTORY: 'data\MIM_XML_CONVERSIONS\'

# Patch extraction configuration.
# r'w.*scores.xml' sample regex for WHOLE_scores.xml associated files.
ASSOCIATED_FILE_PATTERN: 'w.*scores.xml'
DOWNSAMPLE_FACTOR: 2
PATCH_SIZE:
  WIDTH: 512
  HEIGHT: 1024

MASK:
  RADIUS: 32

EXPAND_OUT_FACTOR: 2